pipeline {
    agent any
    stages {
        stage('Install') {
            steps {
                sh "bash installscripts.sh"
            }
        }

        stage('Build and Push') {
            environment {
                DOCKER_CREDS = credentials('docker-creds')
            }
            steps {
                sh "docker-compose build --parallel"
                sh "docker login -u ${DOCKER_CREDS_USR} -p ${DOCKER_CREDS_PSW}"
                sh "docker-compose push"
                sh "/bin/bash -c 'docker rmi \$(docker images -q)'"
            }
        }

        stage('Terraform') {
            steps {
                sh "bash terrascripts.sh"
            }
        }
    }
        stage('K8s'){
            steps{
                sh "bash jenkins/kubescripts.sh"
            }
    post {
        always {
            archiveArtifacts artifacts: "*/htmlcov/*"
        }
    }
}